SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, 
CASE 
	WHEN PRECO_DE_LISTA >=12 THEN 'PRODUTO CARO' 
    WHEN PRECO_DE_LISTA >=7 AND PRECO_DE_LISTA <12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' 
END 
AS STATUS_PRECO FROM tabela_de_produtos;


SELECT * FROM tabela_de_clientes;
SELECT NOME, 
CASE 
	WHEN YEAR(DATA_DE_NASCIMENTO) <1990 THEN 'VELHO'
    WHEN YEAR(DATA_DE_NASCIMENTO)>=1990 AND YEAR(DATA_DE_NASCIMENTO)<=1995 THEN 'JOVEM'
    ELSE 'CRIANÇA'
END
AS IDADE FROM tabela_de_clientes ORDER BY (DATA_DE_NASCIMENTO) DESC;
