SELECT LTRIM('    Olá') AS RESULTADO;
SELECT 'OLÁ    ' AS RESULTADO;
SELECT UPPER('olá, tudo bem?');
SELECT SUBSTRING('OLÁ, TUDO BEM?',6,4) AS RESULTADO;
SELECT CONCAT(NOME, ' (', CPF, ') ') AS RESULTADO FROM tabela_de_clientes;



SELECT CURDATE();
SELECT CURRENT_TIME();
SELECT CURRENT_TIMESTAMP();
SELECT DAY(CURRENT_TIMESTAMP());
SELECT DATEDIFF(CURRENT_TIMESTAMP(), '1993-03-24') AS RESULTADO;
SELECT CURRENT_TIME() AS HOJE, DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY) AS RESULTADO;
SELECT DISTINCT DATA_VENDA, DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MES, YEAR(DATA_VENDA) AS ANO FROM notas_fiscais;