USE sucos_vendas;
SELECT * FROM itens_notas_fiscais;

SELECT * FROM itens_notas_fiscais WHERE NOT NUMERO = 100;

SELECT * FROM tabela_de_produtos WHERE SABOR LIKE '%Maça%';

SELECT * FROM tabela_de_clientes;

SELECT DISTINCT * FROM tabela_de_clientes;

SELECT DISTINCT BAIRRO FROM tabela_de_clientes WHERE CIDADE = 'Rio de Janeiro'; 

SELECT * FROM notas_fiscais WHERE DATA_VENDA = '2017-01-01' LIMIT 10;

SELECT * FROM notas_fiscais ORDER BY IMPOSTO, DATA_VENDA DESC LIMIT 10;
SELECT * FROM tabela_de_produtos ORDER BY EMBALAGEM ASC, NOME_DO_PRODUTO DESC LIMIT 10;
SELECT * FROM itens_notas_fiscais;
SELECT * FROM tabela_de_produtos WHERE NOME_DO_PRODUTO LIKE 'Linha Refrescante%' ;

SELECT * FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabela_de_clientes GROUP BY ESTADO; 
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS MAIOR_PRECO FROM tabela_de_produtos GROUP BY EMBALAGEM;
SELECT EMBALAGEM, COUNT(*) AS CONTADOR FROM tabela_de_produtos GROUP BY EMBALAGEM;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE FROM tabela_de_clientes
GROUP BY ESTADO HAVING SUM(LIMITE_DE_CREDITO) > 900000;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO
FROM tabela_de_produtos GROUP BY EMBALAGEM HAVING SUM(PRECO_DE_LISTA) <=80 
AND MAX(PRECO_DE_LISTA)>=5;

SELECT * FROM tabela_de_produtos;
SELECT CPF, COUNT(*) FROM notas_fiscais WHERE YEAR(DATA_VENDA)=2016 GROUP BY CPF 
HAVING COUNT(*)>2000;


