SELECT * FROM tbcliente;
SELECT CPF, NOME FROM tbcliente LIMIT 5;
SELECT CPF AS CPF_CLIENTE, NOME AS NOME_CLIENTE FROM tbcliente;

SELECT * FROM tbproduto;
SELECT * FROM tbproduto WHERE PRODUTO = '544931'; 

SELECT * FROM tbcliente WHERE CIDADE = 'Rio de Janeiro';

SELECT * FROM tbcliente WHERE IDADE <> 22;
SELECT * FROM tbcliente WHERE IDADE > 22 AND SEXO = 'M';
SELECT * FROM tbcliente WHERE CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins';
SELECT * FROM tbcliente WHERE NOME > 'Fernando Cavalcante';

SELECT * FROM tbproduto WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;

SELECT * FROM tbcliente WHERE DATA_NASCIMENTO > '1952-01-01';
SELECT * FROM tbcliente WHERE YEAR(DATA_NASCIMENTO) > 1952;
SELECT * FROM tbcliente WHERE MONTH(DATA_NASCIMENTO) = 10;